//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnII.Services.Notification
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    internal partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StandaloneNotificationBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10", ItemName="StandaloneNotification")]
    internal class StandaloneNotificationBEList : System.Collections.Generic.List<AltinnII.Services.Notification.StandaloneNotification>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandaloneNotification", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    internal partial class StandaloneNotification : object
    {
        
        private string FromAddressField;
        
        private System.Nullable<bool> IsReservableField;
        
        private int LanguageIDField;
        
        private string NotificationTypeField;
        
        private AltinnII.Services.Notification.ReceiverEndPointBEList ReceiverEndPointsField;
        
        private string ReporteeNumberField;
        
        private AltinnII.Services.Notification.Roles RolesField;
        
        private AltinnII.Services.Notification.Service ServiceField;
        
        private System.DateTime ShipmentDateTimeField;
        
        private AltinnII.Services.Notification.TextTokenSubstitutionBEList TextTokensField;
        
        private System.Nullable<bool> UseServiceOwnerShortNameAsSenderOfSmsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> IsReservable
        {
            get
            {
                return this.IsReservableField;
            }
            set
            {
                this.IsReservableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int LanguageID
        {
            get
            {
                return this.LanguageIDField;
            }
            set
            {
                this.LanguageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.ReceiverEndPointBEList ReceiverEndPoints
        {
            get
            {
                return this.ReceiverEndPointsField;
            }
            set
            {
                this.ReceiverEndPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ReporteeNumber
        {
            get
            {
                return this.ReporteeNumberField;
            }
            set
            {
                this.ReporteeNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.Roles Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.Service Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime ShipmentDateTime
        {
            get
            {
                return this.ShipmentDateTimeField;
            }
            set
            {
                this.ShipmentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.TextTokenSubstitutionBEList TextTokens
        {
            get
            {
                return this.TextTokensField;
            }
            set
            {
                this.TextTokensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> UseServiceOwnerShortNameAsSenderOfSms
        {
            get
            {
                return this.UseServiceOwnerShortNameAsSenderOfSmsField;
            }
            set
            {
                this.UseServiceOwnerShortNameAsSenderOfSmsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06")]
    internal partial class Service : object
    {
        
        private string ServiceCodeField;
        
        private int ServiceEditionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string ServiceCode
        {
            get
            {
                return this.ServiceCodeField;
            }
            set
            {
                this.ServiceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int ServiceEdition
        {
            get
            {
                return this.ServiceEditionField;
            }
            set
            {
                this.ServiceEditionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiverEndPointBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="ReceiverEndPoint")]
    internal class ReceiverEndPointBEList : System.Collections.Generic.List<AltinnII.Services.Notification.ReceiverEndPoint>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Roles", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06", ItemName="RoleName")]
    internal class Roles : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TextTokenSubstitutionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="TextToken")]
    internal class TextTokenSubstitutionBEList : System.Collections.Generic.List<AltinnII.Services.Notification.TextToken>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverEndPoint", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    internal partial class ReceiverEndPoint : object
    {
        
        private System.Nullable<AltinnII.Services.Notification.TransportType> TransportTypeField;
        
        private string ReceiverAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<AltinnII.Services.Notification.TransportType> TransportType
        {
            get
            {
                return this.TransportTypeField;
            }
            set
            {
                this.TransportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        internal string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    internal enum TransportType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSPreferred = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailPreferred = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextToken", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    internal partial class TextToken : object
    {
        
        private int TokenNumField;
        
        private string TokenValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TokenNum
        {
            get
            {
                return this.TokenNumField;
            }
            set
            {
                this.TokenNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TokenValue
        {
            get
            {
                return this.TokenValueField;
            }
            set
            {
                this.TokenValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SendNotificationResultList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06", ItemName="NotificationResult")]
    internal class SendNotificationResultList : System.Collections.Generic.List<AltinnII.Services.Notification.NotificationResult>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationResult", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06")]
    internal partial class NotificationResult : object
    {
        
        private AltinnII.Services.Notification.EndPointResultList EndPointsField;
        
        private string NotificationTypeField;
        
        private string ReporteeNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.EndPointResultList EndPoints
        {
            get
            {
                return this.EndPointsField;
            }
            set
            {
                this.EndPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ReporteeNumber
        {
            get
            {
                return this.ReporteeNumberField;
            }
            set
            {
                this.ReporteeNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EndPointResultList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06", ItemName="EndPointResult")]
    internal class EndPointResultList : System.Collections.Generic.List<AltinnII.Services.Notification.EndPointResult>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndPointResult", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06")]
    internal partial class EndPointResult : object
    {
        
        private string NameField;
        
        private string ReceiverAddressField;
        
        private System.Nullable<bool> RetrieveFromProfileField;
        
        private AltinnII.Services.Notification.TransportType TransportTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> RetrieveFromProfile
        {
            get
            {
                return this.RetrieveFromProfileField;
            }
            set
            {
                this.RetrieveFromProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal AltinnII.Services.Notification.TransportType TransportType
        {
            get
            {
                return this.TransportTypeField;
            }
            set
            {
                this.TransportTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", ConfigurationName="AltinnII.Services.Notification.INotificationAgencyExternalBasic")]
    internal interface INotificationAgencyExternalBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnII.Services.Notification.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.TestResponse> TestAsync(AltinnII.Services.Notification.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasic", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnII.Services.Notification.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicResponse> SendStandaloneNotificationBasicAsync(AltinnII.Services.Notification.SendStandaloneNotificationBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnII.Services.Notification.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Response> SendStandaloneNotificationBasicV2Async(AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnII.Services.Notification.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Response> SendStandaloneNotificationBasicV3Async(AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    internal partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    internal partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasic", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicRequestBody Body;
        
        public SendStandaloneNotificationBasicRequest()
        {
        }
        
        public SendStandaloneNotificationBasicRequest(AltinnII.Services.Notification.SendStandaloneNotificationBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    internal partial class SendStandaloneNotificationBasicRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicRequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicRequestBody(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicResponse", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicResponseBody Body;
        
        public SendStandaloneNotificationBasicResponse()
        {
        }
        
        public SendStandaloneNotificationBasicResponse(AltinnII.Services.Notification.SendStandaloneNotificationBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class SendStandaloneNotificationBasicResponseBody
    {
        
        public SendStandaloneNotificationBasicResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV2", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicV2RequestBody Body;
        
        public SendStandaloneNotificationBasicV2Request()
        {
        }
        
        public SendStandaloneNotificationBasicV2Request(AltinnII.Services.Notification.SendStandaloneNotificationBasicV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    internal partial class SendStandaloneNotificationBasicV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicV2RequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicV2RequestBody(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV2Response", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicV2ResponseBody Body;
        
        public SendStandaloneNotificationBasicV2Response()
        {
        }
        
        public SendStandaloneNotificationBasicV2Response(AltinnII.Services.Notification.SendStandaloneNotificationBasicV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    internal partial class SendStandaloneNotificationBasicV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string SendStandaloneNotificationBasicV2Result;
        
        public SendStandaloneNotificationBasicV2ResponseBody()
        {
        }
        
        public SendStandaloneNotificationBasicV2ResponseBody(string SendStandaloneNotificationBasicV2Result)
        {
            this.SendStandaloneNotificationBasicV2Result = SendStandaloneNotificationBasicV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV3", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicV3RequestBody Body;
        
        public SendStandaloneNotificationBasicV3Request()
        {
        }
        
        public SendStandaloneNotificationBasicV3Request(AltinnII.Services.Notification.SendStandaloneNotificationBasicV3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    internal partial class SendStandaloneNotificationBasicV3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicV3RequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicV3RequestBody(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendStandaloneNotificationBasicV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV3Response", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public AltinnII.Services.Notification.SendStandaloneNotificationBasicV3ResponseBody Body;
        
        public SendStandaloneNotificationBasicV3Response()
        {
        }
        
        public SendStandaloneNotificationBasicV3Response(AltinnII.Services.Notification.SendStandaloneNotificationBasicV3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    internal partial class SendStandaloneNotificationBasicV3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public AltinnII.Services.Notification.SendNotificationResultList SendStandaloneNotificationBasicV3Result;
        
        public SendStandaloneNotificationBasicV3ResponseBody()
        {
        }
        
        public SendStandaloneNotificationBasicV3ResponseBody(AltinnII.Services.Notification.SendNotificationResultList SendStandaloneNotificationBasicV3Result)
        {
            this.SendStandaloneNotificationBasicV3Result = SendStandaloneNotificationBasicV3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface INotificationAgencyExternalBasicChannel : AltinnII.Services.Notification.INotificationAgencyExternalBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal partial class NotificationAgencyExternalBasicClient : System.ServiceModel.ClientBase<AltinnII.Services.Notification.INotificationAgencyExternalBasic>, AltinnII.Services.Notification.INotificationAgencyExternalBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationAgencyExternalBasicClient() : 
                base(NotificationAgencyExternalBasicClient.GetDefaultBinding(), NotificationAgencyExternalBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), NotificationAgencyExternalBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.TestResponse> AltinnII.Services.Notification.INotificationAgencyExternalBasic.TestAsync(AltinnII.Services.Notification.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnII.Services.Notification.TestResponse> TestAsync()
        {
            AltinnII.Services.Notification.TestRequest inValue = new AltinnII.Services.Notification.TestRequest();
            return ((AltinnII.Services.Notification.INotificationAgencyExternalBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicResponse> AltinnII.Services.Notification.INotificationAgencyExternalBasic.SendStandaloneNotificationBasicAsync(AltinnII.Services.Notification.SendStandaloneNotificationBasicRequest request)
        {
            return base.Channel.SendStandaloneNotificationBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicResponse> SendStandaloneNotificationBasicAsync(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            AltinnII.Services.Notification.SendStandaloneNotificationBasicRequest inValue = new AltinnII.Services.Notification.SendStandaloneNotificationBasicRequest();
            inValue.Body = new AltinnII.Services.Notification.SendStandaloneNotificationBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((AltinnII.Services.Notification.INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Response> AltinnII.Services.Notification.INotificationAgencyExternalBasic.SendStandaloneNotificationBasicV2Async(AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Request request)
        {
            return base.Channel.SendStandaloneNotificationBasicV2Async(request);
        }
        
        public System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Response> SendStandaloneNotificationBasicV2Async(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Request inValue = new AltinnII.Services.Notification.SendStandaloneNotificationBasicV2Request();
            inValue.Body = new AltinnII.Services.Notification.SendStandaloneNotificationBasicV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((AltinnII.Services.Notification.INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Response> AltinnII.Services.Notification.INotificationAgencyExternalBasic.SendStandaloneNotificationBasicV3Async(AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Request request)
        {
            return base.Channel.SendStandaloneNotificationBasicV3Async(request);
        }
        
        public System.Threading.Tasks.Task<AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Response> SendStandaloneNotificationBasicV3Async(string systemUserName, string systemPassword, AltinnII.Services.Notification.StandaloneNotificationBEList standaloneNotifications)
        {
            AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Request inValue = new AltinnII.Services.Notification.SendStandaloneNotificationBasicV3Request();
            inValue.Body = new AltinnII.Services.Notification.SendStandaloneNotificationBasicV3RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((AltinnII.Services.Notification.INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicV3Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic))
            {
                return new System.ServiceModel.EndpointAddress("https://www.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotificationAgencyExternalBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotificationAgencyExternalBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INotificationAgencyExternalBasic,
        }
    }
}
